name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Typst
        uses: baptiste0928/cargo-install@v2
        with:
          crate: typst-cli
          git: https://github.com/typst/typst
          branch: main
      - name: Clone Notebookinator
        uses: actions/checkout@v4
        with:
          repository: PA055/notebookinator
          path: ./notebookinator
          ref: main
      - name: Install Notebookinator
        run: |
          cd notebookinator
          ./scripts/package @local
      - name: Compile Notebook
        run: |
          typst compile main.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v4.4.3
        with:
          name: notebook
          path: main.pdf
